PREFIX lsqr: <http://lsq.aksw.org/>
PREFIX lsqv: <http://lsq.aksw.org/vocab#>
PREFIX prov: <http://www.w3.org/ns/prov#>


SELECT ?queryId ?time ?host
WHERE {
       GRAPH $dataset {
              ?query lsqv:hash ?queryId;
                     lsqv:hasRemoteExec ?exec.
              ?exec prov:atTime ?time.
              OPTIONAL {?exec lsqv:hostHash ?host}
       }
}
